import type { LanguageCode } from "@/types";

// Transcribed from the shipped images. Illegible cursive, seals and distant signs
// are intentionally omitted; the captions do not infer missing text or puzzle answers.
// Visually checked: V4-SAM-01..06, V4-LOU-01..06, V4-LOU-P01..P08, V4-FOR-01..09.
export const LOTUS_IMAGE_TEXT_LATE: Record<string, Record<LanguageCode, string[]>> = {
  "V4-SAM-02": {
    "zh-CN": ["梁掌柜交货单", "街口点收：十二包。"],
    "zh-TW": ["梁掌櫃交貨單", "街口點收：十二包。"],
    en: ["Shopkeeper Liang’s delivery order", "Counted and received at the street entrance: twelve bundles."],
    pt: ["Guia de entrega do comerciante Liang", "Contados e recebidos à entrada da rua: doze volumes."],
  },
  "V4-SAM-03": {
    "zh-CN": ["陈掌柜入店簿", "正常入店：十包。"],
    "zh-TW": ["陳掌櫃入店簿", "正常入店：十包。"],
    en: ["Shopkeeper Chen’s shop intake ledger", "Normal shop intake: ten bundles."],
    pt: ["Livro de entradas na loja do comerciante Chen", "Entrada normal na loja: dez volumes."],
  },
  "V4-SAM-04": {
    "zh-CN": ["脚夫阿成存条", "其中两包被雨打湿，暂放檐下，等待查验。"],
    "zh-TW": ["腳夫阿成存條", "其中兩包被雨打濕，暫放簷下，等待查驗。"],
    en: ["Receipt kept by the porter A Cheng", "Two of the bundles were soaked by rain and temporarily left under the eaves, awaiting inspection."],
    pt: ["Recibo guardado pelo carregador A Cheng", "Dois dos volumes ficaram molhados pela chuva e foram deixados temporariamente debaixo do beiral, à espera de inspeção."],
  },
  "V4-SAM-05": {
    "zh-CN": [
      "梁掌柜交货单\n街口点收：十二包。",
      "陈掌柜入店簿\n正常入店：十包。",
      "脚夫阿成存条\n其中两包淋雨打湿，暂放檐下，等待查验。",
      "公议记录\n交货十二包，入店十包，短少二包。\n？",
      "梁掌柜记了十二包，陈掌柜只记了十包。是谁的账错了？还是我们把两种不同的账，当成了同一种账？",
    ],
    "zh-TW": [
      "梁掌櫃交貨單\n街口點收：十二包。",
      "陳掌櫃入店簿\n正常入店：十包。",
      "腳夫阿成存條\n其中兩包淋雨打濕，暫放簷下，等待查驗。",
      "公議記錄\n交貨十二包，入店十包，短少二包。\n？",
      "梁掌櫃記了十二包，陳掌櫃只記了十包。是誰的帳錯了？還是我們把兩種不同的帳，當成了同一種帳？",
    ],
    en: [
      "Shopkeeper Liang’s delivery order\nCounted and received at the street entrance: twelve bundles.",
      "Shopkeeper Chen’s shop intake ledger\nNormal shop intake: ten bundles.",
      "Receipt kept by the porter A Cheng\nTwo of the bundles got wet in the rain and were temporarily left under the eaves, awaiting inspection.",
      "Record of the joint discussion\nTwelve bundles delivered, ten taken into the shop, two missing.\n?",
      "Shopkeeper Liang recorded twelve bundles, while Shopkeeper Chen recorded only ten. Whose account was wrong? Or have we treated two different kinds of account as if they were the same?",
    ],
    pt: [
      "Guia de entrega do comerciante Liang\nContados e recebidos à entrada da rua: doze volumes.",
      "Livro de entradas na loja do comerciante Chen\nEntrada normal na loja: dez volumes.",
      "Recibo guardado pelo carregador A Cheng\nDois dos volumes apanharam chuva e ficaram molhados, sendo deixados temporariamente debaixo do beiral, à espera de inspeção.",
      "Registo da discussão conjunta\nDoze volumes entregues, dez recebidos na loja, dois em falta.\n?",
      "O comerciante Liang registou doze volumes, mas o comerciante Chen registou apenas dez. Qual dos registos estava errado? Ou tratámos dois tipos diferentes de registo como se fossem do mesmo tipo?",
    ],
  },
  "V4-LOU-03": {
    "zh-CN": [
      "中式建筑部分　西式建筑部分",
      "拆开以后，每一栏都很整齐。可是原来的窗不见了。",
      "如果同一扇窗用了不同地方传来的做法，我们应该把它画在哪一张图上？",
      "还是说，为了让两张图看起来各自清楚，就必须把一扇完整的窗拆成两半？",
    ],
    "zh-TW": [
      "中式建築部分　西式建築部分",
      "拆開以後，每一欄都很整齊。可是原來的窗不見了。",
      "如果同一扇窗用了不同地方傳來的做法，我們應該把它畫在哪一張圖上？",
      "還是說，為了讓兩張圖看起來各自清楚，就必須把一扇完整的窗拆成兩半？",
    ],
    en: [
      "Chinese architectural elements · Western architectural elements",
      "Once taken apart, every column is neatly arranged. But the original window has disappeared.",
      "If one window uses methods brought from different places, which map should we draw it on?",
      "Or must we split a complete window in half just to make each of the two maps look clear?",
    ],
    pt: [
      "Elementos de arquitetura chinesa · Elementos de arquitetura ocidental",
      "Depois de desmontada, cada coluna fica bem organizada. Mas a janela original desapareceu.",
      "Se uma mesma janela usa técnicas vindas de lugares diferentes, em qual dos mapas devemos desenhá-la?",
      "Ou será necessário dividir uma janela inteira ao meio para que cada um dos dois mapas pareça claro?",
    ],
  },
  "V4-LOU-04": {
    "zh-CN": [
      "五片已经找齐。",
      "找一处屋里能够看见天空的地方。",
      "按照到达地点的先后，把五张纸叠在同一束光下。",
    ],
    "zh-TW": [
      "五片已經找齊。",
      "找一處屋裡能夠看見天空的地方。",
      "按照到達地點的先後，把五張紙疊在同一束光下。",
    ],
    en: [
      "All five pieces have been found.",
      "Find a place inside the house where you can see the sky.",
      "In the order you visited the places, stack the five sheets in the same beam of light.",
    ],
    pt: [
      "As cinco peças já foram encontradas.",
      "Encontra um lugar dentro da casa de onde se possa ver o céu.",
      "Pela ordem em que chegaste a cada lugar, sobrepõe as cinco folhas sob o mesmo feixe de luz.",
    ],
  },
  "V4-LOU-06": {
    "zh-CN": ["城由人共写"],
    "zh-TW": ["城由人共寫"],
    en: ["The city is written by its people."],
    pt: ["A cidade é escrita pelas suas gentes."],
  },
  "V4-FOR-03": {
    "zh-CN": ["莲城脉图　阿澜", "城市测绘图　M"],
    "zh-TW": ["蓮城脈圖　阿瀾", "城市測繪圖　M"],
    en: ["Map of the Lotus City’s Pulse · A Lan", "City Survey Map · M"],
    pt: ["Mapa do Pulsar da Cidade de Lótus · A Lan", "Mapa Topográfico da Cidade · M"],
  },
  "V4-FOR-05": {
    "zh-CN": [
      "阿澜：",
      "你第一次在我的图上补写街坊使用的名字时，我认为那些内容不属于测绘。",
      "后来我发现，一条路即使位置没有改变，也可能因为使用它的人不同，而拥有另一种意义。",
      "你说我的图只画下城的骨架。这个说法并不准确，但我不再反对。",
      "因为我也终于承认，只有骨架不能称为一座活着的城。",
      "我不会把你的图改成我的图，也不希望你把自己的图改成我的。",
      "请把它们留在一起。",
      "如果后来的人仍然看不懂，就让他们亲自走一遍。",
    ],
    "zh-TW": [
      "阿瀾：",
      "你第一次在我的圖上補寫街坊使用的名字時，我認為那些內容不屬於測繪。",
      "後來我發現，一條路即使位置沒有改變，也可能因為使用它的人不同，而擁有另一種意義。",
      "你說我的圖只畫下城的骨架。這個說法並不準確，但我不再反對。",
      "因為我也終於承認，只有骨架不能稱為一座活著的城。",
      "我不會把你的圖改成我的圖，也不希望你把自己的圖改成我的。",
      "請把它們留在一起。",
      "如果後來的人仍然看不懂，就讓他們親自走一遍。",
    ],
    en: [
      "A Lan,",
      "When you first added the names used by local residents to my map, I thought that such details had no place in surveying.",
      "Later, I realised that even if a road stays in the same place, it can take on a different meaning because different people use it.",
      "You said my map drew only the city’s skeleton. That is not quite accurate, but I no longer object.",
      "For I, too, have finally admitted that a skeleton alone cannot be called a living city.",
      "I will not turn your map into mine, nor do I want you to change your own map to match mine.",
      "Please keep them together.",
      "If those who come later still cannot understand, let them walk the route themselves.",
    ],
    pt: [
      "A Lan,",
      "Quando acrescentaste pela primeira vez ao meu mapa os nomes usados pelos moradores, achei que esses pormenores não pertenciam ao levantamento topográfico.",
      "Mais tarde, percebi que, mesmo sem mudar de lugar, uma rua pode ganhar outro significado por ser usada por pessoas diferentes.",
      "Disseste que o meu mapa desenhava apenas o esqueleto da cidade. Essa afirmação não é inteiramente exata, mas já não me oponho.",
      "Porque também eu finalmente reconheci que um esqueleto, por si só, não pode ser chamado uma cidade viva.",
      "Não transformarei o teu mapa no meu, nem quero que alteres o teu para o tornar igual ao meu.",
      "Por favor, guarda-os juntos.",
      "Se quem vier depois ainda não compreender, que faça o percurso pelos próprios pés.",
    ],
  },
  "V4-FOR-06": {
    "zh-CN": [
      "后来读到这封信的人：",
      "当你拿起这两张图时，我们所认识的澳门应该已经改变了。",
      "海岸会移动，房屋会改建，广场会有新的模样，街坊也会使用新的名字。",
      "不必把今天改回我们见过的样子，也不必为了证明今天正确，就擦掉我们留下的记录。",
      "请写清楚你在什么时间来到这里，看见了什么，又从哪里知道这些事情。",
      "地图不是最后的判决。",
      "它只是一个人，在某个时刻，对城市所作的一次认真回答。",
      "五张纸条上的花并不是宝藏的位置。",
      "它们只是提醒你：",
      "一朵花由不同花瓣组成，一座城也由许多人共同写成。",
    ],
    "zh-TW": [
      "後來讀到這封信的人：",
      "當你拿起這兩張圖時，我們所認識的澳門應該已經改變了。",
      "海岸會移動，房屋會改建，廣場會有新的模樣，街坊也會使用新的名字。",
      "不必把今天改回我們見過的樣子，也不必為了證明今天正確，就擦掉我們留下的記錄。",
      "請寫清楚你在什麼時間來到這裡，看見了什麼，又從哪裡知道這些事情。",
      "地圖不是最後的判決。",
      "它只是一個人，在某個時刻，對城市所作的一次認真回答。",
      "五張紙條上的花並不是寶藏的位置。",
      "它們只是提醒你：",
      "一朵花由不同花瓣組成，一座城也由許多人共同寫成。",
    ],
    en: [
      "To whoever reads this letter in the future:",
      "By the time you pick up these two maps, the Macau we knew will probably have changed.",
      "The coastline will shift, houses will be rebuilt, squares will take on new appearances, and local residents will use new names.",
      "There is no need to change today’s city back into the one we saw, nor to erase the records we left behind just to prove that today is right.",
      "Please state clearly when you came here, what you saw, and where you learned about these things.",
      "A map is not a final verdict.",
      "It is simply one person’s considered response to the city at a particular moment.",
      "The flower on the five notes does not mark the location of a treasure.",
      "The notes only remind you:",
      "A flower is made of different petals, and a city is written together by many people.",
    ],
    pt: [
      "A quem ler esta carta no futuro:",
      "Quando pegares nestes dois mapas, a Macau que conhecemos provavelmente já terá mudado.",
      "A linha da costa deslocar-se-á, as casas serão reconstruídas, as praças terão um novo aspeto e os moradores usarão novos nomes.",
      "Não é preciso devolver à cidade de hoje o aspeto que conhecemos, nem apagar os registos que deixámos só para provar que o presente tem razão.",
      "Indica claramente quando vieste aqui, o que viste e de onde obtiveste essas informações.",
      "Um mapa não é uma sentença final.",
      "É apenas a resposta atenta de uma pessoa à cidade, num determinado momento.",
      "A flor nos cinco bilhetes não assinala a localização de um tesouro.",
      "Os bilhetes apenas te lembram:",
      "Uma flor é composta por pétalas diferentes, e uma cidade também é escrita em conjunto por muitas pessoas.",
    ],
  },
};
